name: Manual Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'windows'
        type: choice
        options:
        - windows
        - macos
        - all

jobs:
  build-macos:
    if: github.event.inputs.platform == 'macos' || github.event.inputs.platform == 'all'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build macOS executables
      run: |
        pyinstaller snaptidy-gui-macos.spec --clean
        pyinstaller snaptidy-cli-macos.spec --clean
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-builds
        path: dist/

  build-windows:
    if: github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Debug - List files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Spec files:"
        ls -la *.spec
        echo "GitHub workspace:"
        echo $env:GITHUB_WORKSPACE
    
    - name: Build Windows executables
      run: |
        pyinstaller snaptidy-gui-windows.spec --clean
        pyinstaller snaptidy-cli-windows.spec --clean
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-builds
        path: dist/ 